---
- hosts: all
  sudo: yes
  vars:
    wf_user: debbie

  tasks:
  
    - name: install zlib-devel
      yum:  name=zlib-devel
    - name: install git
      yum:  name=git

    - name: Create base directory
      file: path="{{ wf_base_dir }}"
            state=directory
            owner="{{ sysadmin }}"
            group="{{ sysadmin }}"

    - name: add git host to known_hosts
      known_hosts: path="/home/{{ sysadmin }}/.ssh/known_hosts"
                   host='git.apidb.org'
                   key="{{ lookup('pipe','ssh-keyscan git.apidb.org') }}"
      sudo: no

    - name: initialize sysadmin directory
      script: init.sh "{{ wf_base_dir }}"
              creates="{{ wf_base_dir }}/sysadmin"
      sudo: no

    - name: add workflow user
      user: name="{{ wf_user }}"
            shell=/bin/bash

    - name: fetch vagrant authorized_keys
      fetch: src=/home/vagrant/.ssh/authorized_keys
             dest=staging/authorized_keys
             flat=yes

    - name: workflow user authorized_keys
      authorized_key: user="{{ wf_user }}"
                      key="{{ lookup('file', 'staging/authorized_keys') }}"

    - name: install workflow bashrc
      copy: src=workflow_bashrc
            dest="/home/{{ wf_user }}/.bashrc"
            owner="{{ wf_user }}"
            mode=0644

    - name: run workpuppet
      script: runworkpuppet.sh "{{ wf_base_dir }}"
      sudo: no
