---
- hosts: all
  sudo: yes

  tasks:
  
    - name: install zlib-devel
      yum:  name=zlib-devel
    - name: install git
      yum:  name=git

    - name: Create base directory
      file: path="{{ wf_base_dir }}"
            state=directory
            owner="{{ sysadmin }}"
            group="{{ sysadmin }}"

    - name: add git host to known_hosts
      known_hosts: path="/home/{{ sysadmin }}/.ssh/known_hosts"
                   host='git.apidb.org'
                   key="{{ lookup('pipe','ssh-keyscan git.apidb.org') }}"
      sudo: no

    - name: initialize sysadmin directory
      script: init.sh {{ wf_base_dir }}
              creates="{{ wf_base_dir }}/sysadmin"
      sudo: no

    - name: add workflow user
      user: name=debbie
            shell=/bin/bash

    - name: workflow user authorized_keys
      authorized_key: user=debbie
                      key="{{ lookup('file', "/home/{{ sysadmin }}/.ssh/id_rsa.pub") }}"
