# Add EuPathDB YUM repos.
# CentOS 5 YUM requires python-hashlib to handle sha256-signed YUM repo
# data (avoiding "Error performing checksum")

- name: install yum-plugin-priorities
  yum:
    name: yum-plugin-priorities

- name: install python-hashlib for sha256 YUM checksums
  yum:
    name: "{{ item }}"
  with_items:
    - python-hashlib
  when: ansible_distribution_major_version == '5'

- name: install RPM-GPG-KEY-EUPATHDB
  copy:
    src: files/RPM-GPG-KEY-EUPATHDB
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-EUPATHDB
  register: gpgkeyeupathdb

- name: import RPM-GPG-KEY-EUPATHDB
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EUPATHDB

- name: configure eupath YUM repos
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    force: yes
  with_items: 
    - { src: templates/eupathdb.repo.j2,
        dest: /etc/yum.repos.d/eupathdb.repo }
    - { src: templates/eupathdb-fasttrack.repo.j2,
        dest: /etc/yum.repos.d/eupathdb-fasttrack.repo }
    - { src: templates/eupathdb-workflow.repo.j2,
        dest: /etc/yum.repos.d/eupathdb-workflow.repo }
